image: google/cloud-sdk:latest # docker image


deploy_staging:
  stage: deploy
  environment: Production # change to your environment 
  only:
    - production # change with your branch name
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json 
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --project $PROJECT_ID app deploy app.yaml

after_script:
- rm /tmp/$CI_PIPELINE_ID.json